### ISSUE TITLE
Next steps for Google Fonts

### ISSUE THREAD

**Issue by yanone** [duongtrtype/DTPhudu#2]
Hello,
I'm writing you here for lack of a better options. Your fonts are ready for Google Fonts.

This is what we need now:
* Please merge this PR: https://github.com/duongtrtype/DTPhudu/pull/1
* Please fill this form with information about you as a designer: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform
* Please fill out the file DESCRIPTION.en_us.html that came as part of the PR with relevant information about the typeface. This will be displayed in the Info section on Google Fonts.

Thank you and please do ask questions if you have any.

**Comment by duongtrtype** [comment]
Thank you for the supports, I've done filling in what you need.

Please let me know what the next step is.

A side note, I've provided my website in the information (www.duongtran.xyz), but currently I'm updating it so the link won't available now, but don't worry, in near future, it will be launched perfectly.

**Comment by duongtrtype** [comment]
I want to ask about 1 problem of the variable file, for this character "ỡ" only, in a bolder weight, it still showed as thin weight. But if I use the ttf static file, it will stay normal. I wonder is there a way to fix this? I myself deleted variable file in the past because of this issue too.
<img width="279" alt="image" src="https://user-images.githubusercontent.com/112008811/214939692-48a51897-dc46-4447-8947-db7982a9a293.png">

**Comment by yanone** [comment]
I see. I will investigate this. Thank you

**Comment by yanone** [comment]
I found the culprit: a scaled component. The production tools (currently) have trouble dealing with them. I rescaled the tilde in `Ỡ` to 100% in all masters, which I believe works completely fine for this design, and now the fonts look well.

Please merge this PR https://github.com/duongtrtype/DTPhudu/pull/3 and do check again if you can spot any more mistakes.

**Comment by duongtrtype** [comment]
@yanone Thank you, that's amazing. I only have problem with the spacing for that tilde, so I updated the source. That's it and everything is good.

**Comment by yanone** [comment]
Great. I generated new fonts. Please merge: https://github.com/duongtrtype/DTPhudu/pull/4

**Comment by duongtrtype** [comment]
I've merged it. Thank you!

**Comment by yanone** [comment]
Okay, I've submitted Phudu to Google Fonts. It usually takes 2 to 3 weeks from here before the fonts show up on fonts.google.com

Thank you for your work. I'm closing this issue.

**Comment by duongtrtype** [comment]
@yanone Hi there, I want to ask about updating my profile information on Google Fonts. How will the process work, can you guide and help me with this? Thank you.

**Comment by yanone** [comment]
Hi. Meanwhile I've stopped contracting for Google Fonts.

You need to basically open a PR against your data in https://github.com/google/fonts/tree/main/catalog/designers. Typically the onboarders do it for you, but I see no reason why you shouldn't do it directly. The PR will be reviewed and finally merged and then it takes some time again before it shows up on the live website.
